### ISSUE TITLE
Use CirrusCI with a Julia package in a subfolder of a GitHub repository

### ISSUE THREAD

**Issue by amontoison** [ararslan/CirrusCI.jl#26]
@ararslan 
In the repository [ralna/GALAHAD](https://github.com/ralna/GALAHAD), we have a Julia interface `GALAHAD.jl` that we want to test automatically with continuous integration.
I tried to use `CirrusCI.jl` for that (see https://github.com/ralna/GALAHAD/pull/219) but I was not able to make it work.
Is it possible to add an option `subdir` or something similar for `cirrusjl`?

**Comment by ararslan** [comment]
Thank you for the ping, that's actually very helpful for me (cf. https://github.com/ararslan/CirrusCI.jl/issues/24#issuecomment-1887556226). You're right, that setup isn't currently supported because the script is relying on the automatic Cirrus environment variables and assuming the repository root == package root.

A `subdir` option to `cirrusjl` is a good idea. Another way to solve this would be to add an additional recognized environment variable that can be used in a `matrix` to permit testing of multiple subdirectories, like `JULIA_PROJECT_SUBDIR` or something like that.

**Comment by amontoison** [comment]
I like the idea of an environment variable `JULIA_PROJECT_SUBDIR`. :+1:
